### ISSUE TITLE
There is no node_infiniband_port_data_received_bytes_total metric in Metrics

### ISSUE THREAD

**Issue by rensongqi** [guilbaults/infiniband-exporter#51]
Hi, I didn't find node_infiniband_port_data_received_bytes_total and node_infiniband_port_data_transmitted_bytes_total in Metrics, how do I calculate to get them?

**Comment by gabrieleiannetti** [comment]
Hi,  
the exporter does expose those metrics.  
They are documented in the [informative-counter](https://github.com/guilbaults/infiniband-exporter#informative-counter) section:  

* `PortXmitData`
* `PortRcvData`

Since the exporter does prefix the metrics with infiniband and also appends a total to both metrics, since they are counter metrics, this will result in Prometheus as following:  

* `infiniband_portxmitdata_total`
* `infiniband_portrcvdata_total`

By reading the documentation about the counter you will recognize that those metrics show the data per one lane. So if you are interested in the total for the NIC you must multiply the value by 4.  

@guilbaults:  
Why exporting the data per lane instead of the total?  
The metric does not even export the data per each lane,  
it is just the average value...  
If the real counter per lane is not exported,  
I would suggest to export the total instead.

Best
Gabriele
